#!/usr/bin/env bash
# ApexTimeline cloud setup — run once after cloning
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"

PROJECT_ID="${FIREBASE_PROJECT_ID:-apex-timeline-$(whoami | tr '.' '-')}"
VERCEL_PROJECT="${VERCEL_PROJECT:-apex-timeline}"

echo "==> ApexTimeline Cloud Setup"
echo "    Firebase project ID: $PROJECT_ID"
echo ""

# --- 1. Install dependencies ---
if [ ! -d node_modules ]; then
  echo "==> Installing CLI tools (firebase-tools, vercel)..."
  npm install
fi

FB="npx firebase"
VC="npx vercel"

# --- 2. Firebase login ---
echo "==> Checking Firebase login..."
if ! $FB projects:list &>/dev/null; then
  if [ ! -t 0 ]; then
    echo ""
    echo "ERROR: Firebase login required. Run this in your terminal (not automated):"
    echo "  cd $ROOT && npm run setup"
    echo ""
    exit 1
  fi
  echo "    Please sign in to Firebase in your browser..."
  $FB login
fi

# --- 3. Create Firebase project (skip if exists) ---
echo "==> Ensuring Firebase project exists: $PROJECT_ID"
if ! $FB projects:list 2>/dev/null | grep -q "$PROJECT_ID"; then
  $FB projects:create "$PROJECT_ID" --display-name "ApexTimeline" || {
    echo "    Project may already exist or name is taken — continuing..."
  }
fi

# Update .firebaserc
cat > .firebaserc <<EOF
{
  "projects": {
    "default": "$PROJECT_ID"
  }
}
EOF

# --- 4. Enable Firestore (create default database) ---
echo "==> Setting up Firestore..."
FIRESTORE_OUT=$($FB firestore:databases:create "(default)" --location us-central1 --project "$PROJECT_ID" 2>&1) || {
  if echo "$FIRESTORE_OUT" | grep -q "ALREADY_EXISTS"; then
    echo "    Firestore database already exists."
  elif echo "$FIRESTORE_OUT" | grep -q "has not been used\|is disabled"; then
    echo ""
    echo "    Firestore API is not enabled yet. Create the database in Firebase Console:"
    echo "    https://console.firebase.google.com/project/$PROJECT_ID/firestore"
    echo ""
    echo "    Steps: Create database → Production mode → pick a region → wait 1 min"
    echo "    Then run: npm run setup:resume"
    echo ""
    exit 1
  else
    echo "$FIRESTORE_OUT"
    echo ""
    echo "    If Firestore isn't set up yet, open:"
    echo "    https://console.firebase.google.com/project/$PROJECT_ID/firestore"
    echo "    Then run: npm run setup:resume"
    exit 1
  fi
}

# --- 5. Deploy security rules ---
echo "==> Deploying Firestore security rules..."
$FB deploy --only firestore:rules --project "$PROJECT_ID"

# --- 6. Enable Auth providers via REST (email + google need console for google OAuth consent) ---
echo ""
echo "==> IMPORTANT: Enable auth providers in Firebase Console:"
echo "    https://console.firebase.google.com/project/$PROJECT_ID/authentication/providers"
echo "    - Enable Email/Password"
echo "    - Enable Google"
echo ""

# --- 7. Fetch web app config ---
echo "==> Fetching Firebase web config..."
APPS_JSON=$($FB apps:list WEB --project "$PROJECT_ID" --json 2>/dev/null || echo '{"result":[]}')

APP_ID=$(echo "$APPS_JSON" | node -e "
  let d=''; process.stdin.on('data',c=>d+=c); process.stdin.on('end',()=>{
    try {
      const j=JSON.parse(d);
      const apps=j.result||[];
      if(apps.length) console.log(apps[0].appId);
    } catch(e) {}
  });
")

if [ -z "$APP_ID" ]; then
  echo "    Creating Firebase web app..."
  CREATE_OUT=$($FB apps:create WEB "ApexTimeline Web" --project "$PROJECT_ID" --json 2>/dev/null || true)
  APP_ID=$(echo "$CREATE_OUT" | node -e "
    let d=''; process.stdin.on('data',c=>d+=c); process.stdin.on('end',()=>{
      try { const j=JSON.parse(d); console.log(j.result?.appId||''); } catch(e) {}
    });
  ")
fi

if [ -n "$APP_ID" ]; then
  SDK_CONFIG=$($FB apps:sdkconfig WEB "$APP_ID" --project "$PROJECT_ID" --json 2>/dev/null || true)
  echo "$SDK_CONFIG" | node -e "
    let d=''; process.stdin.on('data',c=>d+=c); process.stdin.on('end',()=>{
      try {
        const j=JSON.parse(d);
        const c=j.result?.sdkConfig||j.sdkConfig;
        if(!c){ process.exit(1); }
        const fs=require('fs');
        const out=\`// Auto-generated by setup-cloud.sh
export const firebaseConfig = \${JSON.stringify(c,null,2)};

export function isFirebaseConfigured() {
  return Boolean(
    firebaseConfig.apiKey &&
    firebaseConfig.apiKey !== 'YOUR_API_KEY' &&
    firebaseConfig.projectId &&
    firebaseConfig.projectId !== 'YOUR_PROJECT_ID'
  );
}
\`;
        fs.writeFileSync('firebase-config.js', out);
        console.log('    Wrote firebase-config.js');
      } catch(e) { process.exit(1); }
    });
  " || echo "    Could not auto-write config — copy from Firebase Console manually."
else
  echo "    Could not create web app automatically."
fi

# --- 8. Vercel deploy ---
echo ""
echo "==> Deploying to Vercel..."
if ! $VC whoami &>/dev/null; then
  if [ ! -t 0 ]; then
    echo "ERROR: Vercel login required. Run: npm run setup"
    exit 1
  fi
  echo "    Please sign in to Vercel..."
  $VC login
fi

# Push env vars to Vercel from firebase-config.js
if [ -f firebase-config.js ]; then
  node -e "
    const fs=require('fs');
    const src=fs.readFileSync('firebase-config.js','utf8');
    const m=src.match(/export const firebaseConfig = (\{[\s\S]*?\});/);
    if(!m) process.exit(1);
    const c=JSON.parse(m[1]);
    const vars={
      FIREBASE_API_KEY:c.apiKey,
      FIREBASE_AUTH_DOMAIN:c.authDomain,
      FIREBASE_PROJECT_ID:c.projectId,
      FIREBASE_STORAGE_BUCKET:c.storageBucket,
      FIREBASE_MESSAGING_SENDER_ID:c.messagingSenderId,
      FIREBASE_APP_ID:c.appId
    };
    fs.writeFileSync('.vercel-env-tmp', Object.entries(vars).map(([k,v])=>k+'='+v).join('\n'));
  " 2>/dev/null && {
    while IFS='=' read -r key value; do
      [ -z "$key" ] && continue
      echo "    Setting Vercel env: $key"
      echo "$value" | $VC env add "$key" production preview development --force 2>/dev/null || true
    done < .vercel-env-tmp
    rm -f .vercel-env-tmp
  }
fi

DEPLOY_URL=$($VC deploy --prod --yes 2>&1 | tee /dev/stderr | grep -oE 'https://[a-zA-Z0-9.-]+\.vercel\.app' | tail -1 || true)

echo ""
echo "=========================================="
echo " Setup complete!"
echo " Firebase project: $PROJECT_ID"
[ -n "$DEPLOY_URL" ] && echo " Vercel URL: $DEPLOY_URL"
echo ""
echo " Final step — add your Vercel domain to Firebase authorized domains:"
echo " https://console.firebase.google.com/project/$PROJECT_ID/authentication/settings"
[ -n "$DEPLOY_URL" ] && echo " Add: $(echo $DEPLOY_URL | sed 's|https://||')"
echo "=========================================="
