#!/usr/bin/env bash
# Resume setup after Firestore is enabled — run after creating Firestore in Firebase Console
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"

PROJECT_ID="${FIREBASE_PROJECT_ID:-apex-timeline-otsukayusei}"
FB="npx firebase"
VC="npx vercel"

echo "==> Resuming setup for: $PROJECT_ID"
echo ""

# Check Firestore exists
echo "==> Checking Firestore database..."
if ! $FB firestore:databases:list --project "$PROJECT_ID" 2>&1 | grep -q "(default)"; then
  echo ""
  echo "Firestore is not set up yet. Do this first:"
  echo ""
  echo "  1. Open: https://console.firebase.google.com/project/$PROJECT_ID/firestore"
  echo "  2. Click 'Create database'"
  echo "  3. Choose 'Start in production mode' (we deploy rules next)"
  echo "  4. Pick a region (e.g. us-central1)"
  echo "  5. Wait ~1 minute, then run: npm run setup:resume"
  echo ""
  exit 1
fi

echo "    Firestore database found."

echo "==> Deploying Firestore security rules..."
$FB deploy --only firestore:rules --project "$PROJECT_ID"

echo "==> Fetching Firebase web config..."
APPS_JSON=$($FB apps:list WEB --project "$PROJECT_ID" --json 2>/dev/null || echo '{"result":[]}')

APP_ID=$(echo "$APPS_JSON" | node -e "
  let d=''; process.stdin.on('data',c=>d+=c); process.stdin.on('end',()=>{
    try {
      const j=JSON.parse(d);
      const apps=j.result||[];
      if(apps.length) console.log(apps[0].appId);
    } catch(e) {}
  });
")

if [ -z "$APP_ID" ]; then
  echo "    Creating Firebase web app..."
  CREATE_OUT=$($FB apps:create WEB "ApexTimeline Web" --project "$PROJECT_ID" --json)
  APP_ID=$(echo "$CREATE_OUT" | node -e "
    let d=''; process.stdin.on('data',c=>d+=c); process.stdin.on('end',()=>{
      try { const j=JSON.parse(d); console.log(j.result?.appId||''); } catch(e) {}
    });
  ")
fi

SDK_CONFIG=$($FB apps:sdkconfig WEB "$APP_ID" --project "$PROJECT_ID" --json)
echo "$SDK_CONFIG" | node -e "
  let d=''; process.stdin.on('data',c=>d+=c); process.stdin.on('end',()=>{
    const j=JSON.parse(d);
    const c=j.result?.sdkConfig||j.sdkConfig;
    const fs=require('fs');
    const out=\`// Auto-generated by setup-resume.sh
export const firebaseConfig = \${JSON.stringify(c,null,2)};

export function isFirebaseConfigured() {
  return Boolean(
    firebaseConfig.apiKey &&
    firebaseConfig.apiKey !== 'YOUR_API_KEY' &&
    firebaseConfig.projectId &&
    firebaseConfig.projectId !== 'YOUR_PROJECT_ID'
  );
}
\`;
    fs.writeFileSync('firebase-config.js', out);
    console.log('    Wrote firebase-config.js');
  });
"

echo ""
echo "==> Enable auth providers (one-time, in browser):"
echo "    https://console.firebase.google.com/project/$PROJECT_ID/authentication/providers"
echo "    - Email/Password"
echo "    - Google"
echo ""

echo "==> Deploying to Vercel..."
if ! $VC whoami &>/dev/null; then
  $VC login
fi

node -e "
  const fs=require('fs');
  const src=fs.readFileSync('firebase-config.js','utf8');
  const m=src.match(/export const firebaseConfig = (\{[\s\S]*?\});/);
  const c=JSON.parse(m[1]);
  const vars={
    FIREBASE_API_KEY:c.apiKey,
    FIREBASE_AUTH_DOMAIN:c.authDomain,
    FIREBASE_PROJECT_ID:c.projectId,
    FIREBASE_STORAGE_BUCKET:c.storageBucket,
    FIREBASE_MESSAGING_SENDER_ID:c.messagingSenderId,
    FIREBASE_APP_ID:c.appId
  };
  fs.writeFileSync('.vercel-env-tmp', Object.entries(vars).map(([k,v])=>k+'='+v).join('\n'));
"

while IFS='=' read -r key value; do
  [ -z "$key" ] && continue
  echo "    Setting Vercel env: $key"
  echo "$value" | $VC env add "$key" production preview development --force 2>/dev/null || true
done < .vercel-env-tmp
rm -f .vercel-env-tmp

DEPLOY_URL=$($VC deploy --prod --yes 2>&1 | tee /dev/stderr | grep -oE 'https://[a-zA-Z0-9.-]+\.vercel\.app' | tail -1 || true)

echo ""
echo "=========================================="
echo " Done!"
echo " Firebase: https://console.firebase.google.com/project/$PROJECT_ID"
[ -n "$DEPLOY_URL" ] && echo " Live URL: $DEPLOY_URL"
echo ""
echo " Add to Firebase Authorized domains:"
echo " https://console.firebase.google.com/project/$PROJECT_ID/authentication/settings"
[ -n "$DEPLOY_URL" ] && echo " Domain: $(echo $DEPLOY_URL | sed 's|https://||')"
echo "=========================================="
